### ISSUE TITLE
DRF3 compatibility

### ISSUE THREAD

**Issue by SofiaMargariti** [etoccalino/django-rest-framework-httpsignature#12]
I am trying to use Django REST Framework 3 along with rest framework-httpsignature but from the requirements I see that the maximum supported versions of DRF is the `2.3`. Are there any serious issues preventing me from using it with DRF3?

**Comment by etoccalino** [comment]
Not at all. Version 2.3 was the version I was using, and never did muster the time to test multiple versions of the stack.
Give it a try @SofiaMargariti and let me know!

**Comment by SofiaMargariti** [comment]
Hi @etoccalino! We tried djangorestframework-httpsignature along with DRF3 and we didn't encounter any problems. The exact versions we are running are DRF 3.1, httpsig 1.1.2 and djangorestframework-httpsignature 0.2.1.1.

**Comment by etoccalino** [comment]
Hey @SofiaMargariti you were absolutely right. Tested and updated. Thanks!
